url: https://emilyf99.github.io
baseurl:

# Site settings
title: Emily Fletcher
email: emilyfletcher099@gmail.com
description: "Online portfolio for Emily Fletcher, UK based Game Developer"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/emilyf99

# Build settings
markdown: kramdown
permalink: pretty